### ISSUE TITLE
Seem like we can add more than one pic within a post/blog/doc page?  Thank you.

### ISSUE THREAD

**Issue by johnsmithodom** [hbstack/docs#106]

**Comment by razonyang** [comment]
In fact, you're able to add any number of pic within the content in [Markdown syntax](https://hbstack.dev/en/docs/content/markdown-syntax/#images). Not sure if this you're asking.

**Comment by johnsmithodom** [comment]
actually, trying to add Gallery within a doc/blog/page, not successfully. Please help.

**Comment by razonyang** [comment]
Could you please provide the use cases? Why won't you use the gallery layout?

**Comment by johnsmithodom** [comment]
That is what trying to achieved, a gallery for one post when more than one picture is posted.  Can't find a working example in the demo site, where doc and gallery are two separate  things.

**Comment by razonyang** [comment]
Please use the https://hugomods.com/en/docs/images/ page as an example, and describe what do you want to achieve.
