### ISSUE TITLE
Left-side navigation broken

### ISSUE THREAD

**Issue by FuadEfendi** [hbstack/docs#859]
Hi Razon, I am not sure if this is correct "module" to report the issue.

On this page, https://javascripttypescriptbooks.com/2/4/2/1/ I have 4.2.2 and 4.2.3 items. When I click on it, "menu" collapses. 4.2.3 has ``` `<script>` Tag``` words, but why 4.2.2 has same behavior, unclear. I can only guess "script" is reserved keyword and Menu breaks if it has this word... I encountered very similar issue in past when I tried to have `content/terms` folder, it breaks too, "terms" is reserved. Thanks,

**Comment by FuadEfendi** [comment]
On this page too: https://javascripttypescriptbooks.com/2/2/8/
Try to click ``` 2.8.1 The `<form>` Element ``` on left-side menu

**Comment by razonyang** [comment]
Something is wrong on your content, which cause the `<script>` tag was imcomplete, and the footer is also missing.

Please check if there is raw HTML in the content that disrupts the HTML markup, as the image below shown, the script tag was broken on a specific page, which should be `highlighting` as the second script.

![image](https://github.com/user-attachments/assets/d5d0c027-c324-4cc3-b5f2-e22fe50f995c)

**Comment by razonyang** [comment]
Please also check the **Quiz Time!** section, seems all the broken pages have this section.

**Comment by FuadEfendi** [comment]
Thank you Razon,

I can see it now too, it is Quiz section which is not HTML-escaped; "HTML injection"
```
### Where is it recommended to place non-essential internal scripts for optimal page load performance?

- [ ] In the `<head>` section
- [x] At the end of the `<body>` section
- [ ] In an external file
- [ ] In a `<div>` element

> **Explanation:** Placing non-essential scripts at the end of the `<body>` allows the HTML content to load first, improving perceived performance.

```

**Comment by FuadEfendi** [comment]
Reported to "Quizdown", https://github.com/bonartm/quizdown-js/issues/55

**Comment by razonyang** [comment]
OK, I'm closing this because it's not a matter of theme.

**Comment by FuadEfendi** [comment]
Yes, "user error"; thank you for the help!
I need to use escaped `&lt;head&gt;` in Markdown.

**Comment by FuadEfendi** [comment]
Finally I reported this bug and workaround to Hugo:
https://discourse.gohugo.io/t/fake-replace-fixes-possible-bug-with-shortcodes/52155

**Comment by razonyang** [comment]
I don't think it would be considered a bug, it's the responsibility of users to escape their HTML content.

By the way, there is a [htmlEscape](https://gohugo.io/functions/transform/htmlescape/) function that might be helpful.

**Comment by FuadEfendi** [comment]
No, it is bug in Hugo: `{{ replace .Inner " " " "  }}` will escape, and `{{ .Inner  }}` won't. `htmlEscape` will output `&amp;lt;` instead of `&lt;`.

**Comment by FuadEfendi** [comment]
Yes perhaps not a bug (really?): {{ replace .Inner " " " "  }} will escape, and {{ .Inner  }} won't.

This does work, as suggested by @jmooring at Hugo:
```
<div class='quizdown'>
  {{ .Inner | htmlEscape | safeHTML }}
</div>
```
